### ISSUE TITLE
Design Sketch and Mood boards

### ISSUE THREAD

**Issue by Ifedolap** [zuri-training/Team-Giraffew2#2]

**Comment by Ifedolap** [comment]
Although we are done with the mood boards, we still have to work on design sketches, everyone is expected to make the 8 screen design sketch and submit on or before 3pm today. Check the figma page for the pages that need to be created

**Comment by USolace** [comment]
Are we to create the pages individually and submit or we are to do it together

**Comment by Victor-Winner** [comment]
I'm loving this team work
